name: HealthKitData.Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-core:
    name: Build Core

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build HealthKitData.Core/HealthKitData.Core.csproj

  publish-nuget-core:
    name: Publish NuGet
    needs: [build-core] # only publish if build succeeds

    runs-on: ubuntu-latest

    if: startsWith(github.ref, 'release-core-')

    steps:
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    - name: Pack
      run: dotnet pack HealthKitData.Core/HealthKitData.Core.csproj --configuration=Release
    - name: Publish
      run: nuget push HealthKitData.Core/**/*.nupkg -Source https://api.nuget.org -ApiKey ${{ secrets.NUGET_API_KEY }}