name: CI - HealthKitData.Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-core:
    name: Build Core

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101

    - name: Install dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build HealthKitData.Core/HealthKitData.Core.csproj

    - name: Pack
      run: dotnet pack HealthKitData.Core/HealthKitData.Core.csproj --configuration=Release

    - uses: actions/upload-artifact@v2
      with:
        name: HealthKitData.Core.nupkg
        path: HealthKitData.Core/**/*.nupkg
