name: HealthKitData.iOS

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-ios:
    name: Build iOS
    
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install dependencies
      run: nuget restore

    - name: Build
      run: msbuild HealthKitData.iOS/HealthKitData.iOS.csproj /verbosity:normal /t:Rebuild

    - name: Pack
      run: msbuild HealthKitData.iOS/HealthKitData.iOS.csproj -p:Configuration=Release -t:Pack

    - uses: actions/upload-artifact@v2
      with:
        name: HealthKitData.iOS.nupkg
        path: HealthKitData.iOS/**/*.nupkg
