name: HealthKitData.Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  create:

jobs:
  build:
    name: Build Core
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0.x'

    - name: Install dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build HealthKitData.Core/HealthKitData.Core.csproj

    - name: Pack
      run: dotnet pack HealthKitData.Core/HealthKitData.Core.csproj --configuration=Release

    - uses: actions/upload-artifact@v2
      with:
        name: nupkg
        path: HealthKitData.Core/**/*.nupkg

  release:
    name: Release
    needs: build
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/release-core-')

    steps:
    - name: Setup NuGet.exe for use with actions
      uses: NuGet/setup-nuget@v1.0.5
      with:
        nuget-api-key: ${{ secrets.NUGET_API_KEY }}

    - uses: actions/download-artifact@v2
      with:
        name: nupkg

    - name: Publish
      run: nuget push /**/*.nupkg -Source https://www.nuget.org